sudo: false

language: python

cache:
  directories:
    - $HOME/env
    - $HOME/data

python:
  - "2.7"
  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
      - sox

env:
  - MEDLEYDB_PATH=$HOME/data/MedleyDB_sample

before_install:
  - bash .travis_download_mdb.sh
  - bash .travis_dependencies.sh
  - export PATH="$HOME/env/miniconda$TRAVIS_PYTHON_VERSION/bin:$PATH";
  - hash -r
  - source activate test-environment

# command to install dependencies
install:
  - pip install coveralls
  - pip install -e .

# command to run tests
script: nosetests --with-coverage --cover-erase --cover-package=medleydb -v -w tests/

after_success:
  - coveralls
  - pip uninstall -y medleydb

after_failure:
  - pip uninstall -y medleydb
