sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
    - sox

env:
- MEDLEYDB_PATH=$HOME/data/MedleyDB_sample

before_install:
  - mkdir $HOME/data
  - wget http://marl.smusic.nyu.edu/medleydb_webfiles/MedleyDB_sample.tar.gz -O $HOME/data/MedleyDB_sample.tar.gz
  - gzip -d $HOME/data/MedleyDB_sample.tar.gz
  - tar xvf $HOME/data/MedleyDB_sample.tar -C $HOME/data/

# command to install dependencies
install:
  - pip install coveralls
  - pip install -e .

# command to run tests
script: nosetests --with-coverage --cover-erase --cover-package=medleydb -v -w tests/

after_success:
    - coveralls
    - pip uninstall -y medleydb

after_failure:
    - pip uninstall -y medleydb
